In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

# Create a simple one-dimensional array
a = np.array([1, 2, 3])

# Create a two-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of zeros
c = np.zeros((2, 3))

# Create an array of ones
d = np.ones((2, 3))

# Create an array of random numbers
e = np.random.rand(2, 3)

# Create identity array
f = np.identity(3)

# Print the arrays
print("a =", a)
print("b =", b)
print("c =", c)
print("d =", d)
print("e =", e)
print("f =", f)

a = [1 2 3]
b = [[1 2 3]
 [4 5 6]]
c = [[0. 0. 0.]
 [0. 0. 0.]]
d = [[1. 1. 1.]
 [1. 1. 1.]]
e = [[0.37095887 0.10617139 0.24857231]
 [0.42851678 0.89414953 0.61304397]]
f = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Rule 2: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

In [9]:
import numpy as np

# 1D array of shape (3,)
a = np.array([1, 2, 3])

# 2D array of shape (2, 3)
b = np.array([[1, 1, 1],
              [2, 2, 2]])

# Broadcasting a to match the shape of b
result = a + b
print(result)

[[2 3 4]
 [3 4 5]]


Rule 1: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

In [10]:
import numpy as np

# 2D array of shape (2, 1)
a = np.array([[1],
              [2]])

# 2D array of shape (2, 3)
b = np.array([[1, 2, 3],
              [1, 2, 3]])

# Broadcasting a to match the shape of b
result = a + b
print(result)

[[2 3 4]
 [3 4 5]]


Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised because broadcasting cannot be performed.

In [11]:
import numpy as np

# 2D array of shape (2, 3)
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# 2D array of shape (3, 2)
b = np.array([[1, 1],
              [2, 2],
              [3, 3]])

# Attempting to broadcast incompatible shapes
try:
    result = a + b
    print(result)
except ValueError as e:
    print("Broadcasting Error:", e)

Broadcasting Error: operands could not be broadcast together with shapes (2,3) (3,2) 


In [12]:
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontally stack the two arrays
h_stacked = np.hstack((a, b))
print(h_stacked)

# Vertically stack the two arrays
v_stacked = np.vstack((a, b))
print(v_stacked)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Reshaping Arrays: Reshaping is essential when you need to alter the dimensionality of an array for operations such as matrix multiplication, data feeding into machine learning models, or for visualization purposes.

In [13]:
import numpy as np

# Create a 1D array of 12 elements
a = np.arange(1, 13)  # Generates numbers from 1 to 12
print("Original array:")
print(a)

# Reshape it into a 3x4 matrix
b = a.reshape(3, 4)
print("\nReshaped array into 3x4 matrix:")
print(b)


Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array into 3x4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Indexing allows you to access individual array elements, while slicing lets you access a sequence of data within the array.

In [14]:
# Access the first element of the reshaped array
print("First element of the reshaped array:")
print(b[0, 0])

# Slice elements from the second row
print("Elements from the second row:")
print(b[1, :])

# Slice elements from the third column
print("Elements from the third column:")
print(b[:, 2])

First element of the reshaped array:
1
Elements from the second row:
[5 6 7 8]
Elements from the third column:
[ 3  7 11]


In [15]:
import numpy as np

# Create two 2x2 matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

# Matrix multiplication
C = np.dot(A, B)
print("Matrix Multiplication of A and B:\n", C)

# Determinant of A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Eigenvalues of A
eigenvalues = np.linalg.eigvals(A)
print("Eigenvalues of A:", eigenvalues)

Matrix Multiplication of A and B:
 [[ 4  4]
 [10  8]]
Determinant of A: -2.0000000000000004
Eigenvalues of A: [-0.37228132  5.37228132]


In [16]:
# Generate an array of 10 random numbers
data = np.random.randn(10)
print("Data:", data)

# Mean
mean_data = np.mean(data)
print("Mean:", mean_data)

# Median
median_data = np.median(data)
print("Median:", median_data)

# Variance
variance_data = np.var(data)
print("Variance:", variance_data)

# Standard Deviation
std_dev_data = np.std(data)
print("Standard Deviation:", std_dev_data)

Data: [-0.2420041  -0.29307147  0.49647501 -0.45235032 -1.2489906  -0.73244904
 -0.43321205 -0.93386144 -1.13964345  1.24570423]
Mean: -0.3733403237563647
Median: -0.44278118684815393
Variance: 0.5208530360203737
Standard Deviation: 0.7217014867799385


In [17]:
# Create two arrays
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

# Element-wise addition
z_add = np.add(x, y)
print("Element-wise addition:", z_add)

# Element-wise multiplication
z_mul = np.multiply(x, y)
print("Element-wise multiplication:", z_mul)

# Element-wise exponentiation
z_exp = np.exp(x)
print("Element-wise exponentiation:", z_exp)

Element-wise addition: [ 6  8 10 12]
Element-wise multiplication: [ 5 12 21 32]
Element-wise exponentiation: [ 2.71828183  7.3890561  20.08553692 54.59815003]
